name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GH_TOKEN: ${{ github.token }}

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-14, macos-12, windows-2019]
    steps:
    - uses: actions/checkout@v4
    - run: gh release create ${GITHUB_REF#refs/tags/} --draft --title ${GITHUB_REF#refs/tags/v}
      if: startsWith(matrix.os, 'ubuntu')
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build --release
    - name: Create archive
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        HOST=$(rustc -vV | sed -n 's|host: ||p')
        DIST=edu-sync-cli-$VERSION-$HOST

        mkdir $DIST

        if [ "${{ matrix.os }}" = windows-* ]; then
          mv target/release/edu-sync-cli.exe $DIST
          7z a $DIST.zip $DIST
          echo "FILE=$DIST.zip" >> $GITHUB_ENV
        else
          mv target/release/edu-sync-cli $DIST
          tar czf $DIST.tar.gz $DIST
          echo "FILE=$DIST.tar.gz" >> $GITHUB_ENV
        fi
    - run: gh release upload ${GITHUB_REF#refs/tags/} $FILE
